version: "3.3"
services:
  frontend:
    ports:
      - ${FRONTEND_PORT}:3000

    env_file:
      - ./.env
      - ./frontend/.env

    volumes:
      - ./frontend/:/app

  backend:
    ports:
      - ${BACKEND_PORT}:5050

    volumes:
      - ./backend/src:/app/src

    env_file:
      - ./.env
      - ./backend/.env
